export const ADD_PROCESS = 'search:ADD_PROCESS'
export const REMOVE_PROCESS = 'search:REMOVE_PROCESS'
export const CLEAN_PROCESS = 'search:CLEAN_PROCESS'
export const FETCHING_PROCESS = 'search:FETCHING_PROCESS'
export const FETCH_FINISHED_PROCESS = 'search:FETCH_FINISHED_PROCESS'
